Trends
=====================================

<body style="background-color:white;font-family:arial">

<p style="color:gray;background-color:white;margin-left: 20px">
<br>
<B><font size="+3">How are behaviors impacting wellbeing evolving?</font></B>
<br>
<br>
</p>
<!--
<style>
.chart-title {  
  font-family: Arial;
  height:40px; 
  display: inline-block;
  overflow: auto;
}    
</style>   
-->

Column {data-width=33%}
-----------------------------------------------------------------------

### <b>Balance</b> {.no-title}

```{r}

create_tracking <- function(data, metric, title, subtitle){
  
  data %>%
    group_by(Date) %>%
    summarise(across(.cols = metric,
                     .fns = ~mean(., na.rm = TRUE)),
              .groups = "drop") %>%
    mutate(
      lag0 = lag(!!sym(metric), 0),
      lag1 = lag(!!sym(metric), 1),
      lag2 = lag(!!sym(metric), 2),
      lag3 = lag(!!sym(metric), 3)
    ) %>%
    mutate(`4 week rolling average` = select(., paste0("lag", 0:3)) %>%
             apply(1, function(x) mean(x, na.rm = TRUE))) %>% # Use all available data
    select(-paste0("lag", 0:3)) %>%
    rename(`Weekly average` = metric) %>%
    pivot_longer(cols = c(`Weekly average`, `4 week rolling average`),
                 names_to = "metrics",
                 values_to = "value") %>%
    drop_na(value) %>%
    ggplot(aes(x = Date,
              y = value,
              colour = metrics)) +
    geom_line(size = 1) +
    scale_colour_manual(
      values = c(
        "Weekly average" = rgb2hex(67, 189, 211),
        "4 week rolling average" = rgb2hex(0, 82, 101)), 
    labels = us_to_space,
    guide = guide_legend(reverse = TRUE)
    ) +
    theme_wpa_basic() +
    theme(axis.line = element_blank(),
          axis.ticks = element_blank(),
          axis.title = element_blank(),
          panel.grid.major.x = element_line(color="gray"),
          panel.grid.major.y = element_line(colour = "#D9E7F7", size = 5)) +
    labs(
      title = title,
      subtitle = subtitle,
      caption = extract_date_range(data, return = "text")
      ) +
    scale_x_date(position = "top")
  
}

# Weekend work
# % Active on the weekend
create_tracking(
  data = my_sq_data,
  metric = "monthly_weekend_work",
  title = "Balance\nWeekend work",
  subtitle = "% of company active on the weekend"
)
```

### <b>Focus</b> {.no-title}

```{r}
  
# % of work week with focus time
create_tracking(
  data = my_sq_data,
  metric = "Total_focus_hours_daily",
  title = "Focus\nFocus Time",
  subtitle = "Average daily focus hours"
)

```

Column {data-width=33%}
-----------------------------------------------------------------------

### <b>Flexibility</b> {.no-title}

```{r}
# % of employees who limit their activity to 8 or fewer distinct hours
create_tracking(
  data = flex_index_data,
  metric = "ControlHours",
  title = "Flexibility\n%Control Active Hours",
  subtitle = "% of employees controlling active hours"
)
  
```

### <b>Urgency</b> {.no-title}

```{r}
  
# Average after hours collaboration for urgent weeks

my_sq_data %>%
  filter(IsUrgent == TRUE) %>%
  create_tracking(
    metric = "After_hours_collaboration_hours",
    title = "Urgency\nUrgent collaboration",
    subtitle = "Average after hours collaboration for urgent weeks"
)

```

Column {data-width=33%}
-----------------------------------------------------------------------

### <b>Activity patterns</b> {.no-title} 

```{r}
  
# Always on
# % of employees who are active for over 13+ hours a day

wp_list$data %>%
  mutate(IsAlwaysOn = (Personas == "6 Always on (13h+)")) %>%
  create_tracking(
    metric = "IsAlwaysOn",
    title = "Activity patterns\nAlways On",
    subtitle = "% of employees who are active for over 13+ hour blocks a day"
    )

```


### <b>Community</b> {.no-title}

```{r}
# small group meetings
# % of meeting time in a small group setting
create_tracking(
  data = my_sq_data,
  metric = "monthly_weekend_work",
  title = "Community\nSmall group meetings",
  subtitle = "% of company active on the weekend"
)
  
```
