---
params:
  wbq: wbq
  hcq: hcq
  set_title: report_title
  hrvar: hrvar
  mingroup: mingroup
  start_hour: start_hour
title: "`r params$set_title`"      
---

<style>                     
.navbar {
  background-color: rgb(47,85,151);
}

h1, h2, h3, h4, h5, h6, .h1, .h2, .h3, .h4, .h5, .h6 {
  font-family: Arial;
  font-weight: 300;
  line-height: 1.1;
  color: inherit;
}

body {
  font-family: Arial;
  font-size: 12px;
  line-height: 1.42857143;
  color: #333333;
  background-color: #ffffff;
}

.chart-title {  
  font-family: Arial;
  height:100px; 
  display: inline-block;
  overflow: auto;
}    
</style>   

```{r setup, include=FALSE}
start_time <- Sys.time()

# 1. Load Library
library(flexdashboard)
library(wpa)
library(tidyverse)

# 1a. Load auxiliary functions
source("auxiliary.R")

# 2. Load Data
my_sq_data <- params$wbq
my_em_data <- params$hcq
hrvar <- params$hrvar
mingroup <- params$mingroup
start_hour <- params$start_hour

intro_toc <- readLines("toc.md")

# Add col checker ----------------------------------------------------------

col_checker <- function(x, col, replacement = NULL){

  if(col %in% names(x) & is.null(replacement)){

    x

  } else if(col %in% names(x) & !is.null(replacement)){

    dplyr::rename(x, !!sym(replacement) := col)

  } else if(!(col %in% names(x)) & !is.null(replacement)){

    dplyr::mutate(x, !!sym(replacement) := NA) # create dummy column

  } else {

    dplyr::mutate(x, !!sym(col) := NA) # create dummy column

  }
}

# 3a. Simulate variables for custom Wellbeing query
my_sq_data <-
  my_sq_data %>%
  
  # Column checks ----------------------------------------------------------
  col_checker(col = "Instant_Message_hours", replacement = "Instant_message_hours") %>%
  col_checker(col = "Collaboration_hrs", replacement = "Collaboration_hours") %>%
  col_checker(col = "Urgent_email_hours") %>%
  col_checker(col = "Weekend_Email") %>%
  col_checker(col = "Weekend_IMs_sent") %>%
  col_checker(col = "IMs_sent_same_level") %>%
  col_checker(col = "IMs_sent_other_level") %>%
  
  # Daily estimates --------------------------------------------------------
  
  mutate(Work_time = Workweek_span / 5) %>% # Average day span
  mutate(dailyCollabHours = Collaboration_hours / 5)  %>% # Average daily CH
  mutate(dailyAfterHours = After_hours_collaboration_hours / 5) %>%
  
  # Urgent collaboration ---------------------------------------------------
  
  mutate(Urgent_collaboration_hours = Urgent_email_hours) %>%
  # mutate(Urgent_collaboration_hours = Urgent_meeting_hours + Urgent_email_hours) %>%
  mutate(IsUrgent = ifelse(Urgent_collaboration_hours > 0, TRUE, FALSE)) %>%
  
  # Weekend work ------------------------------------------------------------

  # mutate(Weekend_work = ifelse(Weekend_Email > 0 | Weekend_Meeting > 0, TRUE, FALSE)) %>%
  mutate(Weekend_work = ifelse(Weekend_Email > 0 | Weekend_IMs_sent > 0, TRUE, FALSE)) %>%
  group_by(PersonId)  %>%
  mutate(Frequency_of_weekend_work = 1 / (sum(Weekend_work) / n())) %>% #TODO: Verify logic
  mutate(monthly_weekend_work = Frequency_of_weekend_work < (52/12)) %>%
  ungroup() %>%
  
  # Two Hour Focus Blocks ---------------------------------------------------

  mutate(focus_per = (Total_focus_hours/ Workweek_span)) %>%
  mutate(focus_per = ifelse(is.infinite(focus_per), 0, focus_per)) %>%
  rename(`% of 2-hour focus block` = "focus_per")

# Values containing groups over minimum group size
mingroup_str <-
  my_sq_data %>%
  hrvar_count(hrvar = hrvar,
              return = "table") %>%
  filter(n >= mingroup) %>%
  pull(!!sym(hrvar))

# 4. Compute working patterns list and flexibility index data
wp_list <-
  my_em_data %>%
  workpatterns_classify(start_hour = start_hour,
                        return = "list",
                        hrvar = hrvar)

flex_index_data <- 
  my_em_data %>%
  flex_index(return = "data",
             hrvar = hrvar)

```

```{r child = "db_cover_4.Rmd"}

```

```{r child = "db_1.Rmd"}

```

```{r child = "db_2.Rmd"}

```

```{r child = "db_3.Rmd"}

```

```{r child = "db_4.Rmd"}

```

```{r child = "db_5.Rmd"}

```

```{r child = "db_6.Rmd"}

```

```{r child = "db_7.Rmd"}

```

```{r child = "db_8.Rmd"}

```

```{r child = "db_notes.Rmd"}

```
